appX/urls.py
from django.urls import path
from appX.views import *
app_name='appX'

urlpatterns=[
    path('csk/',csk,name='csk'),
    path('csk1',csk1,name='csk1')
]

appY/urls.py
from django.urls import path
from appY.views import *
app_name='appY'

urlpatterns=[
    path('rcb/',rcb,name='rcb'),
    path('rcb1',rcb1,name='rcb1'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import appX,appY
from appZ.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appX/',include('appX.urls')),
    path('appY/',include('appY.urls')),
    path('mumbai/',mumbai,name='mumbai'),
    path('mumbai1/',mumbai1,name='mumbai1')
]

appX/models.py
from django.db import models

# Create your models here.

appY/models.py
from django.db import models

# Create your models here.

appZ/models.py
from django.db import models

# Create your models here.

appX/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def csk1(request):
    return HttpResponse('csk 2023 champians')

def csk(request):
    return render(request,'csk.html')

appY/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def rcb1(request):
    return HttpResponse('royal challengers banglore')

def rcb(request):
    return render(request,'rcb.html')

appZ/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def mumbai1(request):
    return HttpResponse('mumbai indians')

def mumbai(request):
    return render(request,'mumbai.html')

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center>
    <h1>csk html page</h1>
    <h1><a href="{% url 'appY:rcb' %}">rcb page</a></h1>
    <h1><a href="{% url 'appY:rcb1' %}">rcb1 page</a></h1>
    <h1><a href="{% url 'mumbai' %}">mumbai page</a></h1>
    <h1><a href="{% url 'mumbai1' %}">mumbai1 page</a></h1>
   </center> 
</body>
</html>

templates/mumbai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>mumbai html page</h1>
        <h1><a href="{% url 'appY:rcb' %}">rcb page</a></h1>
        <h1><a href="{% url 'appY:rcb1' %}">rcb1 page</a></h1>
        <h1><a href="{% url 'appX:csk' %}">csk page </a></h1>
        <h1><a href="{% url 'appX:csk1' %}">csk1 page </a></h1>
    </center>
</body>
</html>

templates/rcb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>rcb html page</h1>
        <h1><a href="{% url 'appX:csk' %}">csk page</a></h1>
        <h1><a href="{% url 'appX:csk1' %}">csk1 page</a></h1>
        <h1><a href="{% url 'mumbai' %}">mumbai page</a></h1>
        <h1><a href="{% url 'mumbai1' %}">mumbai1 page</a></h1>
    </center>
</body>
</html>